### ISSUE TITLE
One last thing...

### ISSUE THREAD

**Issue by MikeLinder** [Kolcha/DigitalClockNext#1]
I know you're anxious to wrap up your excellent app that's been on my desktop for years — but, would it be possible to have a 12-hour display without any trailing text, be it an "A" or a "P" or anything else?

If not, I'll have to adapt to a clean 24-hour readout. Still, thanks for a great piece of work.

—Mike

**Comment by Kolcha** [comment]
unfortunately, this is how [Qt date/time formatting forks](https://doc.qt.io/qt-6/qtime.html#toString), see description for 'h' and 'hh' expressions. according to this description, you can get 12-hour format only when AM/PM is displayed. who knows why Qt designed it in this way, but this is how it works...

for now I'm directly using formatting provided by Qt (just for simplicity, I was focused on new architecture), older clock uses custom hand-written formatter exactly for this use case. I'll port that formatter (or maybe even write new one) to this newer clock, this is not a first task in my list, but I'll prioritize it.

as workaround, I can suggest just to [create skin](https://sourceforge.net/p/digitalclock4/wiki/How%20to%20create%20skin/) (or modify what are you using) without AM/PM symbols, so they will not be rendered, but you will still have 12-hour format as appropriate time format string (with 'a' or 'p') is used. but this track will not work for font used instead of skin.

**Comment by Kolcha** [comment]
fixed in 73a0af6683951b7ed5cccc304d1c3946c64ccb8c , wait for next "unstable/beta" release or just download nightly build from GitHub Actions
