### ISSUE TITLE
option for 24 hours clock

### ISSUE THREAD

**Issue by Li-An** [Kolcha/DigitalClockNext#6]
Hello, I would like a 24 hours format as, in France, we don’t use AM and PM. After reading the wiki I thought I could duplicate the default skin and change the hour format but I did not find any C:\Users\<your username>\AppData\Roaming\NickKorotysh\DigitalClockNext\skins directory. I suppose I must create one. I must admit I am a little lost.

**Comment by Kolcha** [comment]
Hello, it really depends on what you want to achieve and what skin you are using.

if you are using any "classic" skin (e.g. the default one, or any of from the old clock, or font), the things are straightforward: just select "24h" on "Format" tab.
![Screenshot_20240605_133626](https://github.com/Kolcha/DigitalClockNext/assets/947647/ee5617d9-027f-47be-bc85-9946af1fe555)

but if you are using "modern" skin (the new format), like "DSEG font" skin built-in in the clock, such skins must be modified, as their layout/appearance is predefined (this is the price for their flexibility).

for example, the shipped "DSEG font" skin was designed to use 12h format with AM/PM, this is a part of its layout. even it's color also is a part of skin definition.
![Screenshot_20240605_133719](https://github.com/Kolcha/DigitalClockNext/assets/947647/278847a3-df76-4856-8de7-151ca9e11524)

to remove am/pm from it (and change to 24h time format), you need to copy whole [skin source](https://github.com/Kolcha/DigitalClockNext/tree/master/res/skins/dseg) (unfortunately no "overlays" are implemented yet) to your user folder (as you found) and then modify [skin.json](https://github.com/Kolcha/DigitalClockNext/blob/master/res/skins/dseg/skin.json), in particular, change time format from "hh:mm" to "HH:mm", and replace AM/PM element with something or remove it completely, otherwise layout will be different.

[here](https://www.dropbox.com/scl/fi/p6vuvrfcwvkoswga46awm/dseg_24.zip?rlkey=9llz7a42xfjgs0t1gxzhfjcqs&st=t9r98i0o&dl=0) (Drobpox) is patched "DSEG font" skin for 24h format. just extract the archive and put that folder to yours "~\AppData\Roaming\NickKorotysh\DigitalClockNext\skins".
![Screenshot_20240605_141226](https://github.com/Kolcha/DigitalClockNext/assets/947647/9b144d9c-7f0f-4a9f-a1e0-415449631493)

**Comment by Li-An** [comment]
Thanks a lot.
